// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.donation.eoy.version.viewed", 5);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1732616515);
user_pref("app.update.lastUpdateTime.region-update-timer", 1732616515);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1732616515);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1732616543);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1732616515);
user_pref("browser.region.update.updated", 1732616489);
user_pref("browser.search.region", "TN");
user_pref("calendar.caldav.googleResync", 1732616488);
user_pref("calendar.list.sortOrder", "9ba9ff7b-1ef6-46cf-aa95-48a7188601aa");
user_pref("calendar.registry.9ba9ff7b-1ef6-46cf-aa95-48a7188601aa.calendar-main-default", true);
user_pref("calendar.registry.9ba9ff7b-1ef6-46cf-aa95-48a7188601aa.calendar-main-in-composite", true);
user_pref("calendar.registry.9ba9ff7b-1ef6-46cf-aa95-48a7188601aa.disabled", true);
user_pref("calendar.registry.9ba9ff7b-1ef6-46cf-aa95-48a7188601aa.name", "Home");
user_pref("calendar.registry.9ba9ff7b-1ef6-46cf-aa95-48a7188601aa.type", "storage");
user_pref("calendar.registry.9ba9ff7b-1ef6-46cf-aa95-48a7188601aa.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Africa/Tunis");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1732616497257");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1732617015);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20241009170210");
user_pref("extensions.lastAppVersion", "115.16.0");
user_pref("extensions.lastPlatformVersion", "115.16.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"fee51210-14ef-4296-a94f-c2300cf62d5d\",\"google@search.mozilla.org\":\"033924fa-fd9a-45d0-98f3-810f2bfd44e0\",\"ddg@search.mozilla.org\":\"cb3dd73e-0ce9-417a-bdbe-b844dbf90ca4\",\"amazondotcom@search.mozilla.org\":\"221bb4e3-fbb2-4913-8dae-75bbe2b4e1de\",\"wikipedia@search.mozilla.org\":\"9696c483-d9fe-4b32-ac8b-87e856be08ce\",\"bing@search.mozilla.org\":\"818de47d-9640-450a-a45a-a8a850bb244a\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "72446494-5a9e-4d1e-9b52-3273a916fe3");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.16.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("services.settings.clock_skew_seconds", -11456);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1732627970);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1732627970);
user_pref("services.settings.thunderbird.search-config.last_check", 1732627970);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1732627970);
user_pref("toolkit.startup.last_success", 1732617011);
user_pref("toolkit.telemetry.cachedClientID", "b15465aa-a72f-4cc1-ac55-bddbcfe6a298");
user_pref("toolkit.telemetry.previousBuildID", "20241009170210");
